<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://ws.app.sirs/"
             targetNamespace="http://ws.app.sirs/" name="AppWebService">
    <types>
        <xs:schema targetNamespace="http://ws.app.sirs/" version="1.0">

            <!-- main service operations data types -->


            <!-- test control operations data types -->

            <xs:complexType name="test_ping">
                <xs:sequence>
                    <xs:element name="input_message" type="xs:string"
                                minOccurs="0" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="test_ping" type="tns:test_ping" />

            <xs:complexType name="test_ping_response">
                <xs:sequence>
                    <xs:element name="return" type="xs:string" minOccurs="0" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="test_ping_response" type="tns:test_ping_response" />

        </xs:schema>
    </types>

    <!-- Messages (use elements defined in the schema) -->

    <!-- main service messages -->


    <!-- test control messages -->
    <message name="test_ping">
        <part name="parameters" element="tns:test_ping" />
    </message>
    <message name="test_ping_response">
        <part name="parameters" element="tns:test_ping_response" />
    </message>




    <!-- Port Type (Interface) -->
    <portType name="AppPortType">
        <!-- main service operations -->


        <!-- test control operations -->
        <operation name="test_ping">
            <input wsam:Action="http://ws.station.binas.org/Station/test_ping_request"
                   message="tns:test_ping" />
            <output wsam:Action="http://ws.station.binas.org/Station/test_ping_response"
                    message="tns:test_ping_response" />
        </operation>



    </portType>

    <!-- SOAP/HTTP Binding -->
    <binding name="AppPortBinding" type="tns:AppPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
                      style="document" />

        <!-- main service operations -->


        <!-- test control operations -->
        <operation name="test_ping">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>



    </binding>

    <!-- Service -->
    <service name="AppService">
        <port name="AppPort" binding="tns:AppPortBinding">
            <soap:address location="http://localhost:8081/app-ws/endpoint" />
        </port>
    </service>
</definitions>
